version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  versioning-strategy: increase
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  versioning-strategy: increase
  ignore:
  - dependency-name: "vue"
    versions: ["^3"]
  - dependency-name: "vuex"
    versions: ["^4"]
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
